### ISSUE TITLE
Add logic to avoid shuffle of options on each "next/previous" click

### ISSUE THREAD

**Issue by mathur07** [mathur07/quiz#10]
- Currently, options are shuffled and re-populated on each "next/previous" button click
- Change this behavior such that they don't shuffle until reset is hit.

Good for beginners. 
All the Best

Try to avoid vuex.

**Comment by Areadrill** [comment]
Hi. Can I take this issue?

**Comment by mathur07** [comment]
@Areadrill Sure :)
