### ISSUE TITLE
Fix Hacktoberfest warning

### ISSUE THREAD

**Issue by legoiv** [mathur07/quiz#3]
Hacktoberfest warning:
**Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.**

Expected: No warning anymore.

**Comment by mathur07** [comment]
@legoiv I have fixed this issue. hope you don't receive any more such mails
